# Generated by Django 4.2.6 on 2023-10-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablaramos",
            name="MATERIA",
            field=models.CharField(max_length=20),
        ),
    ]
