# Generated by Django 4.2.6 on 2023-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_tablaramos_materia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablaramos",
            name="FIN",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tablaramos",
            name="INICIO",
            field=models.DateField(blank=True, null=True),
        ),
    ]
